import Image from 'next/image';

import Cross from '../../../public/icon/cross.svg';
import apeImg from '../../../public/imgs/about.png';

export default function About() {
  return (
    <section className="container relative block-distance pb-[50px] md:pb-[95px]">
      <div id="about" className="md:flex md:mb-[68px] xl:mb-14">
        <h2 className="smOnly:mb-[76px] w-[216px] md:w-[296px] xl:w-[540px] text-[40px] md:text-[60px] xl:text-[120px] leading-none uppercase shrink-0">
          a Story that started with
          <span className="text-red-light"> one simple ape</span>
        </h2>

        <p className="smOnly:mb-9 ml-auto md:pt-[10px] w-[216px] md:w-[275px] xl:w-[409px] xl:text-[24px] text-right font-['MSMono'] leading-[1.19] xl:leading-[1.21] uppercase smOnly:first-letter:ml-[50%]">
          WHO GOT FED UP WITH BORING AND HYPOCRITIC COMMONPLACE THIS IS HOW THE
          IDEA OF ESCAPING AND DYNAMIC{' '}
          <span className="md:pl-20 xl:pl-28">JOURNEY ON THE YACHT</span>
        </p>
      </div>

      <div className="md:w-[269px] xl:w-[417px] smOnly:mb-10 text-center">
        <Cross className="mx-auto mb-4 xl:mb-9 w-[24px] h-[24px] xl:w-[36px] xl:h-[36px]" />

        <p
          className="font-['MSMono'] text-xs md:text-base xl:text-[24px]
leading-[1.17] xl:leading-[1.21] md:leading-[1.17] uppercase"
        >
          EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY. ARTS ARE
          RANDOMLY GENERATED BY USERS
        </p>
      </div>

      <div className="md:absolute md:w-[313px] xl:w-[492px] md:bottom-[52px] xl:bottom-[86px] md:right-[88px] xl:right-[120px]">
        <Image
          src={apeImg}
          width={492}
          height={622}
          alt="Ape"
          sizes="(min-width: 1280px) 492px,
                (min-width: 768px) 313px,
                216px"
        />
      </div>
      <div className="absolute left-0 bottom-0 w-full overflow-hidden bg-red-light">
        <p className="flex items-center pt-[5px] xl:pt-[6px] pb-[11px] xl:pb-4 !text-nowrap flex-nowrap text-4xl xl:text-[64px] leading-none uppercase bg-red-light animate-scroll">
          <span className="px-6 text-xl">
            <Cross className="w-[36px] h-[36px] mt-[5px] xl:mt-[10px]" />
          </span>{' '}
          Destroy stereotypes{' '}
          <span className="px-6 text-xl">
            <Cross className="w-[36px] h-[36px] mt-[5px] xl:mt-[10px]" />
          </span>{' '}
          HAVE NO LIMITS
          <span className="px-6 text-xl">
            <Cross className="w-[36px] h-[36px] mt-[5px] xl:mt-[10px]" />
          </span>{' '}
          Break rules{' '}
          <span className="px-6 text-xl">
            <Cross className="w-[36px] h-[36px] mt-[5px] xl:mt-[10px]" />
          </span>
        </p>
      </div>
    </section>
  );
}
